version: '3.8'

networks:
  inception:

volumes:
  mariaVol:
  wordVol:

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariaVol:/var/lib/mysql
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordVol:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
  nginx:
    image: nginx
    build: ./requirements/nginx/
    container_name: nginx
    env_file:
      - ./.env
    volumes:
      - wordVol:/var/www/html
    ports:
      - '443:443'
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always