version: '3.8'

networks:
  inception:
    name: inception

volumes:
  mariaVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mbenbajj/data/mariadb
  wordVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mbenbajj/data/wordpress

services:
  mariadb:
    image: mariadb:mbenbajj
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariaVol:/var/lib/mysql
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress:mbenbajj
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordVol:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    restart: always
  nginx:
    image: nginx:mbenbajj
    build: ./requirements/nginx/
    container_name: nginx
    env_file:
      - ./.env
    volumes:
      - wordVol:/var/www/html
    ports:
      - '443:443'
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  redis:
    image: redis:mbenbajj
    build: ./requirements/bonus/redis
    container_name: redis
    env_file:
      - ./.env
    networks:
      - inception
    restart: always
  adminer:
    image: adminer:mbenbajj
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - '8081:8081'
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
  static:
    image: static:mbenbajj
    build: ./requirements/bonus/static
    container_name: static
    ports:
      - '80:80'
    networks:
      - inception
    restart: always
  cadvisor:
    image: cadvisor:mbenbajj
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    ports:
      - '8080:8080'
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
      - wordpress
      - nginx
      - redis
      - static
      - adminer
  ftp:
    image: ftp
    build: ./requirements/bonus/ftp
    container_name: ftp
    volumes:
      - wordVol:/home/mbenbajj/ftp
    networks:
      - inception
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    restart: always
    depends_on:
      - wordpress
    